spring.application.name=RentGame

spring.datasource.url=jdbc:postgresql://195.150.230.208:5432/2024_lyszczarz_krzysztof
spring.datasource.username=2024_lyszczarz_krzysztof
spring.datasource.password=4686

# JPA + Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rentgameat@gmail.com
spring.mail.password=qylo fswd lemg lkso
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


